### ISSUE TITLE
Acquire logo assets for websites

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/whygriefmatters.org#13]
Where we are using logos for other sites we need to verify the permissions to use them - as well as obtain web ready versions appropriate to our requirements

**Comment by danlechambre** [comment]
Hi @jkraesullivan can I close this issue? I think you did all the work in obtaining them - they just need adding to the "image" field for each website document in Sanity yes?

**Comment by jkraesullivan** [comment]
Hey @danlechambre, I hadn’t been able to get every org to provide or respond with confirmation for us to use their logos. When you and I were recently talking about logos, I met with Camille and worked on something (I’d have to look back, everything is a fog lately 😂). I will email back to check in as it is on my list/radar and have been wondering about it myself. I would leave this open though.

**Comment by danlechambre** [comment]
@jkraesullivan I'll close this one - I know the logos haven't yet been added into the CMS - but I'm sure you're already tracking that task somewhere
