### ISSUE TITLE
Change Copyright Notice To Come From CMS

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/whygriefmatters.org#68]
### Enhancement Description

The copyright notice should be automatically generated by the relevant content in the CMS so that it can be updated freely without needing a developer.

### Additional Context

Additional fields have been added to the `Organization` content type in Sanity meaning that the information for the copyright notice is available to pull from there.

We should use the opportunity to create a specific footer model as the footer is likely to become more complex in the near future.

### Acceptance Criteria

1. There should be a new model called `footer` inside the `model` folder. It should include:
    - A new Zod model to model the footer data object with the following properties:
        - `logo` - should use existing `zImage` model 
        - `copyrightDate` - should be z.date()
        - `copyrightNotice` - should be a string
        - `organizationName` - should be a string
        - `legalText` - should be a `zPortableText` model
    - A Groq query for fetching the model
        - `logo` should be assigned the `light-secondary` variant of the logo
        - `copyrightDate` - generate at query time using Groq `dateTime(now())`
        - `copyrightNotice` - field of same name on `organization`
        - `organizationName` - should be the `legalName` field in `organization`
        - `legalText` - should be the `smallPrint` field on `organization`
    - A Type inferred from the Zod model
2. There should be a new method added to `client` called `getFooterData` that should execute the query and parse the fetched data against the new model.
3. The existing `getSmallPrint` method can be removed
4. The `SiteFooter` component should be updated to use the new client method
    - The copyright symbol should be switched from a literal character to the HTML entity (as it's coming out grey at the moment)
    - The `copyrightDate` should be processed into the year within the component
    - The existing hard-coded text can be replaced with the new data
    - Most of the image processing can be left as is within the component

**Comment by danlechambre** [comment]
This issue will require setting up the Sanity Studio repo if you want to be able to test your Groq query during development

**Comment by drewrogersuxd** [comment]
@danlechambre I created a pull request for the work on this. Please let m eknow if what I did is correct.

**Comment by drewrogersuxd** [comment]
this should be resolved now that it is merged
