### ISSUE TITLE
Change Order Of Featured Stories And Featured Articled

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/whygriefmatters.org#74]
### Enhancement Description

Throughout the website, please switch the order of Featured Articles and Featured Stories, with Featured Articles coming first.

### Acceptance Criteria

Order of Featured Stories and Articles should be changed

### Suggested Solution

I’m pretty sure that src/pages/[category]/index.astro is the only file that needs to be changed for this. We just need to swap the sections around

**Comment by danlechambre** [comment]
@drewrogersuxd want to take a look at this one? No much to it but should give a good opportunity to dig in and take a look around?

**Comment by drewrogersuxd** [comment]
Ok I’ll look at over the weekend.
Thanks

**Comment by drewrogersuxd** [comment]
@danlechambre - I forked the whygriefmatters.org repo and changed the file that you indicated.
Looks like articles is first now:
![406D8073-2DDB-4CA1-91DB-548321C26CD9](https://github.com/user-attachments/assets/ce8da558-33d3-4e77-b974-e7fa4cd72c42)
How shuld I go about a PR?

**Comment by danlechambre** [comment]
If you've created a fork, I think of you go to the main branch in this repo - and up towards the top right above the list of files if you click "Compare and Pull Request" on the screen to raise it, there should be an option like "compare across forks" or something. Then it should be a case of selecting "main" in our repo, and whatever branch you made changes to in your forked repo.

Hope that's enough info to get you through. For future reference you have 'write' access to our repo so you can create branches and pull requests directly

**Comment by drewrogersuxd** [comment]
@danlechambre thanks i wasn't sure if i had write access to the repo.
I switched over to using the grief-matters repo.
Did a pull request - not sure if the file worker-configuration.d.ts should be in there - it wasn't ignored

**Comment by danlechambre** [comment]
Approved - merge at your leisure.

Yeah I think it's if our env files are out of sync in some way - I'll look into it at some point

**Comment by drewrogersuxd** [comment]
ok. thanks. just merged it.
